version: "3.9"

services:
  melissaBot:
    image: melissa
    container_name: melissaBot
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    env_file:
      - config.env
    restart: unless-stopped

# Uncomment the following lines to use a local MongoDB database
#   mongo:
#     image: "mongo:latest"
#     container_name: MelissaMongo
#     volumes:
#       - "mongo_Melissa:/data/db"
#     environment:
#       MONGO_INITDB_ROOT_USERNAME: Melissa
#       MONGO_INITDB_ROOT_PASSWORD: mypasswd

# volumes:
#   mongo_Melissa:
